### ISSUE TITLE
how to parse bytestream get from Monitors_Get_ByteStream

### ISSUE THREAD

**Issue by ericwoo-github** [dss-extensions/dss_capi#133]
how to parse bytestream get from Monitors_Get_ByteStream, if i want to get each individual value monitored

**Comment by PMeira** [comment]
See e.g. https://github.com/dss-extensions/DSS-Python/blob/0.15.7/dss/IMonitors.py#L28-L77

The channel/column names are not embedded in the bytestream anymore, but the space previously used for those is left empty so that older software most works. Nowadays, you need to use `(ctx_)Monitors_Get_Header` to get the channel names. The first two columns are ("Hour", "Second"), or ("Frequency", "Harmonic"), depending on the solution mode.

Typically, most users use the `Monitors_Get_Channel` function, coupled with `Monitor_Get_dblHour`. You can process the bytestream manually to save some time and potentially memory. That's why the Python version of `Channel` processes the bytestream directly using NumPy.

**Comment by ericwoo-github** [comment]
thanks
