### ISSUE TITLE
how to get snapshot solution result from load

### ISSUE THREAD

**Issue by ericwoo-github** [dss-extensions/dss_capi#134]
how to get snapshot solution result from load, via monitor?

**Comment by PMeira** [comment]
You can force the monitors (and meters) to take samples. Also remember to "save" the samples in order to access the results through the monitor bytestream later.

Here's a simple example. We add a monitor with mode 1 (see the link for the docs at the end), solve and force a sample, then update `LoadMult` to 1.5 to force a different scenario, and repeat solving and sampling. Finally, call `SaveSample()` to make the results available in the monitor's bytestream.

For the high level APIs that mimic the COM class layout, here's a Python (DSS-Python) example:

```python
from dss import dss, SolveModes
dss.Text.Command = 'redirect electricdss-tst/Version8/Distrib/IEEETestCases/13Bus/IEEE13Nodeckt.dss'
dss.Text.Command = new monitor.mon_load element=load.671 mode=1'
dss.ActiveCircuit.Solution.Mode = SolveModes.SnapShot
dss.ActiveCircuit.Solution.Solve()
dss.ActiveCircuit.Sample()
dss.ActiveCircuit.Solution.LoadMult = 1.5
dss.ActiveCircuit.Solution.Solve()
dss.ActiveCircuit.Sample()
dss.ActiveCircuit.SaveSample()
```

Directly in C it should be something like:

```c
Text_Set_Command("redirect electricdss-tst/Version8/Distrib/IEEETestCases/13Bus/IEEE13Nodeckt.dss");
Text_Set_Command("new monitor.mon_load element=load.671 mode=1");
Solution_Set_Mode(SolveModes_SnapShot);
Solution_Solve();
Circuit_Sample();
Solution_Set_LoadMult(1.5);
Solution_Solve();
Circuit_Sample();
Circuit_SaveSample();
```

Our monitor docs: https://dss-extensions.org/dss-format/Monitor.html
As the docs there suggest, you can also use the action property of a monitor using the text interface to instruct it to sample and save.

By the way, it's better to post questions at https://github.com/orgs/dss-extensions/discussions and leave the issues for bugs etc. Remember to provide some context, but e.g. programming language should be enough.
